### ISSUE TITLE
Failing vignette

### ISSUE THREAD

**Issue by muschellij2** [WIAS-BERLIN/qMRI#1]
Seems like the data is `NULL` in https://github.com/WIAS-BERLIN/qMRI/blob/master/vignettes/qMRI-Example.Rnw#L280.

I have made some adjustments on https://github.com/muschellij2/qMRI and view the results on https://travis-ci.com/muschellij2/qMRI.  I will add them if the edits check out.

**Comment by ktabelow** [comment]
I don't know, why this happens? Why do you think, data is NULL at L280?

**Comment by ktabelow** [comment]
Vignette now runs on iMac, we hope the commit resolves the issue

**Comment by muschellij2** [comment]
Still does not work for me.  Same failures - extract doesn't seem to work
for a lot of this: https://travis-ci.com/muschellij2/qMRI
John

**Comment by ktabelow** [comment]
Thank you John!!!
